version: "3.11"

services:

  web:
    restart: unless-stopped
    image: fast_api
    build: .
    entrypoint: sh -c "chmod +x ./entrypoint.sh && ./entrypoint.sh"
    volumes:
      - static_volume:/app/static
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    expose:
      - 5432
    volumes:
      - ./:/code
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db

volumes:
  static_volume: