"""add trade stock table

Revision ID: 4fe5a8227515
Revises: 8b29daf27d7c
Create Date: 2023-11-09 15:43:28.510202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fe5a8227515'
down_revision: Union[str, None] = '8b29daf27d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_stock',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user', sa.Integer(), nullable=True),
                    sa.Column('symbol', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('exch', sa.String(), nullable=True),
                    sa.Column('stock_type', sa.String(), nullable=True),
                    sa.Column('open_price', sa.Float(), nullable=True),
                    sa.Column('high_price', sa.Float(), nullable=True),
                    sa.Column('low_price', sa.Float(), nullable=True),
                    sa.Column('bid_price', sa.Float(), nullable=True),
                    sa.Column('ask_price', sa.Float(), nullable=True),
                    sa.Column('change_percentage', sa.Float(), nullable=True),
                    sa.Column('prevclose', sa.Float(), nullable=True),
                    sa.Column('week_52_high', sa.Float(), nullable=True),
                    sa.Column('week_52_low', sa.Float(), nullable=True),
                    sa.Column('trade_date', sa.TIMESTAMP(), nullable=True),
                    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_stock')
    # ### end Alembic commands ###
